project 'AppAcoustic.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AppAcoustic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleSignIn'
  #pod 'Firebase/Core'
  pod 'Firebase/Core', '4.0.3'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Alamofire'
  pod 'ObjectMapper', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SDWebImage'

end
